export { default as numToPercentage } from './numToPercentage'
export { default as splitNum } from './splitNum'
export { default as clipPercentageFromNum } from './clipPercentageFromNum'
export { default as getFileAccept } from './getFileAccept'
export { default as TreeManage } from './TreeManage'
export * as storage from './storage'
export * from './compress'
export * from './base64'
export * from './file'
export { default as resizeImage } from './resizeImage'
export * from './resolveLast'
